<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NekoPlayer.App.Resources\NekoPlayer.App.Resources.csproj" />
    <ProjectReference Include="..\osu-framework\osu.Framework/osu.Framework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
    <PackageReference Include="Crypto.AES" Version="1.0.4" />
    <PackageReference Include="DiscordRichPresence" Version="1.6.1.70" />
    <PackageReference Include="Google.Apis.Auth" Version="1.76.0" />
    <PackageReference Include="Google.Apis.Oauth2.v2" Version="1.74.0.1869" />
    <PackageReference Include="SharpCompress" Version="0.50.4" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.76.0.4262" />
    <PackageReference Include="Humanizer" Version="3.0.10" />
    <PackageReference Include="PaletteNet" Version="3.0.1" />
    <PackageReference Include="McEndu.FreeTypeSharp" Version="4.1.5" />
    <PackageReference Include="Sentry" Version="6.11.1" />
    <PackageReference Include="Lazy.Fody" PrivateAssets="all" Version="1.11.0" />
    <PackageReference Include="ppy.LocalisationAnalyser" Version="2026.611.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="YoutubeExplode" Version="6.6.2" />
    <PackageReference Include="YoutubeExplode.Converter" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Localisation\NekoPlayerExtraStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NekoPlayerExtraStrings.resx</DependentUpon>
    </Compile>
    <Compile Update="Localisation\NekoPlayerTrayIconStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NekoPlayerTrayIconStrings.resx</DependentUpon>
    </Compile>
    <Compile Update="Localisation\NekoPlayer_DiscordRPCStrings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>NekoPlayer_DiscordRPCStrings.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Localisation\NekoPlayerExtraStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>NekoPlayerExtraStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localisation\NekoPlayerTrayIconStrings.ja.resx">
      <LastGenOutput>NekoPlayerTrayIconStrings.ja.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localisation\NekoPlayerTrayIconStrings.ko.resx">
      <LastGenOutput>NekoPlayerTrayIconStrings.ko.Designer.cs</LastGenOutput>
      <Generator>ResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="Localisation\NekoPlayerTrayIconStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>NekoPlayerTrayIconStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Localisation\NekoPlayer_DiscordRPCStrings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>NekoPlayer_DiscordRPCStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
  </ItemGroup>
</Project>
