<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputType>WinExe</OutputType>
    <AssemblyName>NekoPlayer</AssemblyName>
    <ApplicationIcon>nekoplayer_app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.0.0</Version>
    <FileVersion>0.0.0</FileVersion>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Tmds.DBus" Version="0.95.1" />
    <PackageReference Include="Tmds.DBus.Protocol" Version="0.95.1" />
    <PackageReference Include="Velopack" Version="1.2.158" />
  </ItemGroup>
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\NekoPlayer.App\NekoPlayer.App.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appIcon.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="avcodec-62.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="avformat-62.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="avutil-60.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="bassloud.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\bin\win-x64\ffmpeg.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libavcodec.so.62">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libavformat.so.62">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libavutil.so.60">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libbassloud.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libswscale.so.9">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="nekoplayer_app.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="nekoplayer_app.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\linux-x64\native\libavcodec.so.62">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\linux-x64\native\libavformat.so.62">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\linux-x64\native\libavutil.so.60">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\linux-x64\native\libbassloud.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\linux-x64\native\libswscale.so.9">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\avcodec-62.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\avformat-62.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\avutil-60.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\bassloud.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\swscale-9.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="swscale-9.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="yt-dlp.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="yt-dlp_linux">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
  </ItemGroup>
</Project>
